name: Matrix Demo
on: workflow_dispatch
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [12,14,16]
        operating-system: [ ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get Code
        uses: action/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version:  ${{ matrix.operating-system }}
      - name: Install dependevies
        run: npm ci
      - name: Build project
        run: npm run build
